### ISSUE TITLE
Support custom domains

### ISSUE THREAD

**Issue by pksunkara** [terraform-community-providers/terraform-provider-railway#11]
Railway supports custom domain creation, but it doesn't let us retrieve the CNAME record for the custom domain.

To fix: Railway needs to add the DNS record to the `CustomDomain` type in graphql.

Why is this important? It's so that we can use terraform to take this DNS record and add it to our DNS records (cloudflare) without any manual intervention.

---

```gql
query {
  domains(
    environmentId:"d2b367de-b363-4455-b842-e60cda62a385",
    serviceId:"89fa0236-2b1b-4a8c-b12d-ae3634b30d97",
    projectId:"0bb01547-570d-4109-a5e8-138691f6a2d1"
  ) {
    customDomains {
      id
      cnameCheck {
        link
        message
        status
      }
      domain
    }
    serviceDomains {
      id
      domain
      suffix
    }
  }
}
```

**Comment by gschier** [comment]
Hey there! I just shipped an update to your API to enable this. The `CustomDomain` type now includes a `status` sub-object with a bunch of useful info related to DNS and certificate generation. There's also a new `customDomain` (not sure if applicable).

<img width="555" alt="CleanShot 2023-07-24 at 16 07 28@2x" src="https://github.com/terraform-community-providers/terraform-provider-railway/assets/587576/21579d90-63a9-4f39-b895-d1043027d85a">

**Comment by EggsLeggs** [comment]
Is there a way to specify the port to use when creating a custom domain?
