### ISSUE TITLE
Support creating and attaching a Railway Volume

### ISSUE THREAD

**Issue by matifali** [terraform-community-providers/terraform-provider-railway#14]
https://docs.railway.app/reference/volumes

## Funding

- You can sponsor this specific effort via a [Polar.sh](https://polar.sh/terraform-community-providers) pledge below
- We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/terraform-community-providers/terraform-provider-railway/issues/14">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/14/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/14/pledge.svg">
</picture>
</a>

**Comment by pksunkara** [comment]
I don't plan to use it, so would welcome a PR.
