### ISSUE TITLE
Source Repo doesn't connect

### ISSUE THREAD

**Issue by virus2016** [terraform-community-providers/terraform-provider-railway#16]
I can't seem to get source_repo to work:

```
resource "railway_service" "nextjs" {
  name       = "nextjs"
  project_id = railway_project.nextjs.id
  source_repo = "GROUP/PROJECT"
  config_path = "apps/nextjs/railway.json"
  root_directory = null
  source_image = null
}
```

It creates the service but the repo is not connected to it.

## Funding

- You can sponsor this specific effort via a [Polar.sh](https://polar.sh/terraform-community-providers) pledge below
- We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/terraform-community-providers/terraform-provider-railway/issues/16">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/16/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/16/pledge.svg">
</picture>
</a>

**Comment by pksunkara** [comment]
There seems to be something weird going on, my services used to have source repo but it isn't shown right now. But deployments still seemed to work.

**Comment by pksunkara** [comment]
Railway might have completely moved to `serviceConnect` mutation. But since the old properties are still there, will need to investigate if the old properties work at all, and if they do not, we should also move this.

**Comment by wertlex** [comment]
@pksunkara well, it seems like that they really moved to `serviceConnect` mutation only. `serviceCreate` still has those `repo` and `image` params, but `repo` do not has any real effect (while `image` still works). 

Would you mind if I'll try to issue a fix for that?

**Comment by pksunkara** [comment]
Feel free because I will probably get to it only next month.

**Comment by wertlex** [comment]
@pksunkara 
Seems to be fixed: https://github.com/terraform-community-providers/terraform-provider-railway/pull/21

Any inputs are appreciated!
