### ISSUE TITLE
Plugins are depreceated. Use database templates.

### ISSUE THREAD

**Issue by virus2016** [terraform-community-providers/terraform-provider-railway#17]
```
resource "railway_plugin" "redis" {
  name       = "notifications-db"
  type       = "redis"
  project_id = railway_project.bounce.id
}
```

These are not depreceated from railway. How do you add a DB service now?

## Funding

- You can sponsor this specific effort via a [Polar.sh](https://polar.sh/terraform-community-providers) pledge below
- We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/terraform-community-providers/terraform-provider-railway/issues/17">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/17/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/17/pledge.svg">
</picture>
</a>

**Comment by pksunkara** [comment]
I think you are supposed to use volumes which I plan to add support for
around Jan if I find some time.

**Comment by pksunkara** [comment]
@virus2016 I am having issues building this because there's no graphql endpoint for creating a TCP proxy `tcpProxyCreate`. I am going to ask railway guys about it, but also please let them know from your side if you are on team plan.
