### ISSUE TITLE
GraphQL method names are backwards

### ISSUE THREAD

**Issue by aleksrutins** [terraform-community-providers/terraform-provider-railway#18]
I could be wrong, but I'm pretty sure that this repository's GraphQL method names are backwards - for instance, this repo calls `createService`, but the actual mutation is `serviceCreate`. This would likely be the cause of #16, if true.

**Comment by pksunkara** [comment]
Railway might have updated their GraphQL, but I have not updated the plugin accordingly

**Comment by aleksrutins** [comment]
Oddly, it is still working at least partially - I'm able to create a service, but not able to set the source repo.

**Comment by pksunkara** [comment]
I am calling the graphQL correctly (https://github.com/terraform-community-providers/terraform-provider-railway/blob/master/internal/provider/generated.go#L3175). It's just that I renamed the functions locally.

**Comment by pksunkara** [comment]
More references: https://github.com/terraform-community-providers/terraform-provider-railway/blob/master/internal/provider/resource_service.graphql#L16-L22
