### ISSUE TITLE
Unable to add project 

### ISSUE THREAD

**Issue by davidvdw** [terraform-community-providers/terraform-provider-railway#33]
Hi,
I try to make a new project with 2 environments

my main.tf
```
terraform {
  required_providers {
    railway = {
      source  = "terraform-community-providers/railway"
      version = "0.4.4"
    }
  }
}


provider "railway" {}


resource "railway_project" "main" {
  name = "newproject"
}


resource "railway_environment" "production" {
  name       = "production"
  project_id = railway_project.main.id
}


resource "railway_environment" "staging" {
  name       = "staging"
  project_id = railway_project.main.id
}
```

when I apply I got:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # railway_environment.production will be created
  + resource "railway_environment" "production" {
      + id         = (known after apply)
      + name       = "production"
      + project_id = (known after apply)
    }

  # railway_environment.staging will be created
  + resource "railway_environment" "staging" {
      + id         = (known after apply)
      + name       = "staging"
      + project_id = (known after apply)
    }

  # railway_project.main will be created
  + resource "railway_project" "main" {
      + default_environment = {
          + id   = (known after apply)
          + name = "production"
        }
      + description         = ""
      + has_pr_deploys      = false
      + id                  = (known after apply)
      + name                = "newproject"
      + private             = true
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

railway_project.main: Creating...

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to railway_project.main, provider "provider[\"registry.terraform.io/terraform-community-providers/railway\"]" produced an unexpected new value: .team_id: was null, but
│ now cty.StringVal("d6b4101a-04de-4b5b-81ea-4bf900f82d70").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

## Funding

- You can sponsor this specific effort via a [Polar.sh](https://polar.sh/terraform-community-providers) pledge below
- We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/terraform-community-providers/terraform-provider-railway/issues/33">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/33/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/terraform-community-providers/terraform-provider-railway/issues/33/pledge.svg">
</picture>
</a>

**Comment by pksunkara** [comment]
You need to specify `team_id` for `railway_project`

**Comment by pksunkara** [comment]
Also, please read the docs first, we already create a default environment for a project.

**Comment by davidvdw** [comment]
> You need to specify `team_id` for `railway_project`

Thank you, @pksunkara, for the quick reply and for maintaining this project.
It could help if the docs mention which fields are required and which are optional. For example, in the [TF AWS S3 docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket)

**Comment by pksunkara** [comment]
Yeah, it is optional only because it should not be present on personal projects.

**Comment by pksunkara** [comment]
With the introduction of railway workspaces, `team_id` is still optional because railways seems to auto select it if:

1. User has only one workspace
2. User's token is constrained to a single workspace.
